version: "3"

services:
  q3ra3:
    image: ra3se/q3ra3-server
    environment:
      MAP: ra3map10
    ports:
      - "27960:27960/udp"
    volumes:
      - "${PWD}/pak0.pk3:/quake3/baseq3/pak0.pk3"
      - "${PWD}/arena/server.cfg:/quake3/arena/server.cfg"
      - "${PWD}/arena/arena.cfg:/quake3/arena/arena.cfg"
      - "db:/arena" 
volumes:
    db: